---
title: "Korea"
author: 第一組
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    theme: bootstrap
    social: [ "facebook", "menu" ]
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
knitr::opts_chunk$set("eval"=T,message=FALSE, warning=FALSE,comment="") 
source("./korea/plot_kor.R",encoding="utf-8")
source("./currency/plot_curr.R",encoding="utf-8")
source("./currency/plot_visa.R",encoding="utf-8")
```

Korean Wave {data-navmenu="韓國" data-icon="fa-television" data-orientation=columns}
===========================================

column 1 {.tabset}
--------------------

### 韓國:年齡
```{r}
pl_kor_age_tour
```

### 韓國:性別
```{r}
pl_kor_gender_tour
```

column 2 {.tabset}
--------------------

### 日本:年齡
```{r}
pl_jp_age_tour
```

### 日本:性別
```{r}
pl_jp_gender_tour
```

sidebar {.sidebar data-width=240}
---------------------------

**日本**

年齡、性別：**各族群趨勢一致**(線條平行)

推論：
    
* 對日本之偏好**無特定族群差異**

<br>

**韓國**

性別：2001年，女性旅遊人數超越男性

年齡：2000-03年，**20-29歲**(青綠色)與其他年齡層**趨勢迥異**

韓流起始：2000年？

* 韓劇**火花**、**藍色生死戀**開播
    
* 自此之後，女性旅客皆比男性多，且**差距不斷地升高**
    

<div class="absolute">

<span class="left">[prev.](#dest-map)</span><span class="right">[nxt.](#page_2)</span>
</div>
    


Cost {data-navmenu="韓國" data-icon="fa-usd" data-orientation=columns}
===========================================

column 1 {.tabset data-width=450}
--------------------

### 日本:按年齡
```{r echo=FALSE, message=FALSE, warning=FALSE}
pl_jp_age_tour
```

### 韓國:按年齡
```{r echo=FALSE, message=FALSE, warning=FALSE}
pl_kor_age_tour
```

### 總人數
```{r echo=FALSE, message=FALSE, warning=FALSE}
pl_total
```

column 2 {.tabset data-width=550}
--------------------

### 匯率
```{r echo=FALSE}
pl_curr
```



其他因素 {data-orientation=rows}
===========================================

row1 {data-height=680}
---------------------

###
```{r echo=FALSE}
ggplotly(pl_visa_country)
```

row2 {data-height=320}
--------------------

###
```{r echo=FALSE}
timevis(visa)
```


